services:
  switchcraft_pg_db:
    container_name: switchcraft_pg_db
    image: postgres:17
    env_file: .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_DATABASE
    volumes:
      - 'switchcraft_pg_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  switchcraft_pgadmin:
    container_name: switchcraft_pg_admin
    image: elestio/pgadmin:latest
    restart: always
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: $PG_ADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PG_ADMIN_PASS
      PGADMIN_LISTEN_PORT: 15432
    ports:
    - '15432:15432'
    volumes:
    - switchcraft_pgadmin_data:/var/lib/pgadmin

volumes:
  switchcraft_pg_data:
  switchcraft_pgadmin_data:
networks:
  default:
    external: true
    name: switchcraft_network
